### ISSUE TITLE
'ent_kb_id' referenced before assignment

### ISSUE THREAD

**Issue by TheNizzo** [UB-Mannheim/spacyopentapioca#3]
Hello, 
while trying this example : 
`nlp("M. Knajdek")`,
An error occurs in the entity_linker.py file
`UnboundLocalError: local variable 'ent_kb_id' referenced before assignment` on line 67 in the file.
This is due to the `.` separator.

**Comment by renat-kaufmann** [comment]
Thank you! It's fixed now. Anyway in your example it returns empty `doc.ents` because Wikidata does not have that entity.
