### ISSUE TITLE
500 Server Error: Internal Server Error for url: https://opentapioca.org/api/annotate

### ISSUE THREAD

**Issue by javiersorucol** [UB-Mannheim/spacyopentapioca#9]
Every time I use spacyopentapioca I get the error: "500 Server Error: Internal Server Error for url: https://opentapioca.org/api/annotate".
I have found that the web portal of OpenTapioca I knew https://opentapioca.org/# also recieves the same error, therefore I've opened an [Issue in the OpenTapioca repo](https://github.com/opentapioca/opentapioca/issues/56), the developer responded with a new web portal from which I've found It nows query to a new url https://opentapioca.wordlift.io/api/annotate, this is likely to be the reason of the error.
Hope this information helps to get spacyopentapioca working again, thanks in advance.

**Comment by renat-kaufmann** [comment]
Thanks a lot, @javiersorucol! I'll update it.
